cleaner_configs:
  n_jobs: 1 # for inference, keep it at 1
  remove_stopwords: False # whether to remove stopwords or keep
  keep_numbers: True # whether to keep numbers, or replace with a static value
  remove_foreign_chars: False # remove any characters other than the target lang


server_configs:
  host: "0.0.0.0"
  port: 18899
  endpoint: "clean_text"
  auth_token: ~ # it is better to read from the env variables.